<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Store.Shared\Store.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Ardalis.Result" Version="10.0.0" />
      <PackageReference Include="Ardalis.Result.AspNetCore" Version="10.0.0" />
      <PackageReference Include="FastEndpoints" Version="5.30.0" />
      <PackageReference Include="FastEndpoints.Swagger" Version="5.30.0" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.10.0" />
      <PackageReference Include="MediatR" Version="12.4.1" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.10" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.6" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Endpoints\" />
      <Folder Include="Features\" />
    </ItemGroup>

</Project>
