FROM node:18.16.0 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine as development-stage
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY nginx.dev.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
