global using Xunit;
global using FluentAssertions;
global using NSubstitute;
global using MediatR;
global using Social.Domain.Entities;
global using System.Net;
global using Social.FunctionalTests.Configurations;
global using System.Net.Http.Json;
global using Social.FunctionalTests.Models;